/* ══════════════════════════════════════════════
   QUANTORYX v6 — VISUAL STRATEGY BUILDER
   Reuses: PageHd, Empty, Modal, toast, CopyBtn,
           .card / .btn / .form-* / .tabs (v5)
══════════════════════════════════════════════ */

const BuilderPage=({go})=>{
  const {data:blocks,loading}=useAsync(()=>api.builder.blocks(),[]);
  const [nodes,setNodes]=useState([
    {uid:'n1',id:'ema', icon:'📈',name:'EMA',params:'period: 20',cat:'Indicators'},
    {uid:'n2',id:'cross_up',icon:'⬆',name:'Crosses Above',params:'close > EMA(20)',cat:'Conditions'},
    {uid:'n3',id:'buy',icon:'🟢',name:'Enter Long',params:'market',cat:'Actions'},
    {uid:'n4',id:'sl', icon:'🛑',name:'Stop Loss',params:'3.0%',cat:'Risk'},
  ]);
  const [sel,setSel]=useState(null);
  const [dragOver,setDragOver]=useState(false);
  const [tab,setTab]=useState('canvas');
  const [meta,setMeta]=useState({name:'Untitled Strategy',symbol:'EUR/USD',tf:'H1'});
  const [saveModal,setSaveModal]=useState(false);
  const [saving,setSaving]=useState(false);

  const addNode=b=>{
    setNodes(p=>[...p,{...b,uid:uid()}]);
    toast.info('Block added',`${b.name} appended to the strategy.`);
  };
  const removeNode=u=>{
    setNodes(p=>p.filter(n=>n.uid!==u));
    if(sel===u) setSel(null);
  };

  const onDrop=e=>{
    e.preventDefault(); setDragOver(false);
    try{
      const b=JSON.parse(e.dataTransfer.getData('application/json'));
      addNode(b);
    }catch{}
  };

  const code=useMemo(()=>{
    const ind=nodes.filter(n=>n.cat==='Indicators');
    const con=nodes.filter(n=>n.cat==='Conditions');
    const act=nodes.filter(n=>n.cat==='Actions');
    const rsk=nodes.filter(n=>n.cat==='Risk');
    return [
      `# ${meta.name}`,
      `# ${meta.symbol} · ${meta.tf} · generated by Quantoryx Builder`,
      ``,
      `class Strategy:`,
      `    symbol    = "${meta.symbol}"`,
      `    timeframe = "${meta.tf}"`,
      ``,
      `    def indicators(self, data):`,
      ...(ind.length?ind.map(n=>`        self.${n.id} = ta.${n.id.toUpperCase()}(data, ${n.params.replace(/[a-z ]+:\s*/i,'')})`):['        pass']),
      ``,
      `    def entry(self, ctx):`,
      ...(con.length?con.map(n=>`        if ctx.${n.id}(${JSON.stringify(n.params)}):`):['        if True:']),
      ...(act.length?act.map(n=>`            ctx.${n.id}(size=self.position_size)`):['            pass']),
      ``,
      `    def risk(self, ctx):`,
      ...(rsk.length?rsk.map(n=>`        ctx.set_${n.id}(${JSON.stringify(n.params)})`):['        pass']),
    ].join('\n');
  },[nodes,meta]);

  const save=async()=>{
    setSaving(true);
    await api.builder.save({...meta,nodes});
    setSaving(false); setSaveModal(false);
    toast.success('Strategy saved',`“${meta.name}” added to your library.`);
  };

  const highlightCode=line=>{
    if(line.trim().startsWith('#')) return <span className="code-cm">{line}</span>;
    const parts=line.split(/("(?:[^"\\]|\\.)*")/g);
    return parts.map((p,i)=>{
      if(p.startsWith('"')) return <span key={i} className="code-str">{p}</span>;
      return <span key={i}>{p.split(/\b(class|def|if|self|return|pass|True)\b/g).map((t,j)=>
        ['class','def','if','self','return','pass','True'].includes(t)
          ?<span key={j} className="code-kw">{t}</span>
          :<span key={j}>{t.split(/(\b\d+\.?\d*\b)/g).map((n,k)=>/^\d/.test(n)?<span key={k} className="code-num">{n}</span>:<span key={k}>{n}</span>)}</span>
      )}</span>;
    });
  };

  const selNode=nodes.find(n=>n.uid===sel);

  return(
    <div className="page fade-page">
      <PageHd title="Strategy Builder" sub="Compose indicators, conditions, and risk rules — no code required">
        <div className="tabs">
          {['canvas','code'].map(t=>(
            <button key={t} className={cx('tab',tab===t&&'on')} onClick={()=>setTab(t)}>
              {t==='canvas'?'🧱 Canvas':'⌨ Code'}
            </button>
          ))}
        </div>
        <button className="btn btn-g btn-sm" onClick={()=>go('backtest')}>▶ Backtest</button>
        <button className="btn btn-p btn-sm" onClick={()=>setSaveModal(true)} disabled={!nodes.length}>💾 Save Strategy</button>
      </PageHd>

      <div className="sbd-grid">
        {/* ── Block library ── */}
        <div className="card card-p">
          <div className="card-hd"><div className="card-title">🧰 Blocks</div></div>
          {loading&&<SkelText lines={7}/>}
          {!loading&&(
            <div className="blk-lib">
              {blocks.map(g=>(
                <React.Fragment key={g.cat}>
                  <div className="blk-cat">{g.cat}</div>
                  {g.items.map(b=>(
                    <button key={b.id} className="blk-chip" draggable
                      onDragStart={e=>e.dataTransfer.setData('application/json',JSON.stringify({...b,cat:g.cat}))}
                      onClick={()=>addNode({...b,cat:g.cat})}>
                      <span className="blk-chip-ico">{b.icon}</span>
                      <span style={{flex:1,minWidth:0}}>
                        <span style={{display:'block',fontWeight:600,color:'var(--tx-1)',fontSize:11.5}}>{b.name}</span>
                        <span style={{display:'block',fontSize:9.5,color:'var(--tx-3)',fontFamily:'JetBrains Mono,monospace'}}>{b.params}</span>
                      </span>
                      <span style={{color:'var(--tx-3)',fontSize:12}}>+</span>
                    </button>
                  ))}
                </React.Fragment>
              ))}
            </div>
          )}
        </div>

        {/* ── Canvas / Code ── */}
        <div className="card card-p">
          <div className="card-hd">
            <div>
              <div className="card-title">{tab==='canvas'?'🧱 Strategy Flow':'⌨ Generated Code'}</div>
              <div className="card-sub">{nodes.length} block{nodes.length===1?'':'s'} · {meta.symbol} · {meta.tf}</div>
            </div>
            <div className="card-acts">
              {tab==='code'&&<CopyBtn text={code} label="Copy code"/>}
              {tab==='canvas'&&nodes.length>0&&
                <button className="btn btn-g btn-sm" onClick={()=>{ setNodes([]); setSel(null); toast.warn('Canvas cleared','All blocks removed.'); }}>Clear</button>}
            </div>
          </div>

          {tab==='canvas'?(
            <div className={cx('canvas',dragOver&&'drag')}
              onDragOver={e=>{ e.preventDefault(); setDragOver(true); }}
              onDragLeave={()=>setDragOver(false)}
              onDrop={onDrop}>
              {nodes.length===0&&(
                <Empty icon="🧱" title="Drag blocks here"
                  sub="Pick indicators, conditions, actions, and risk rules from the library on the left to compose your strategy."/>
              )}
              {nodes.map((n,i)=>(
                <React.Fragment key={n.uid}>
                  {i>0&&<div className="node-link">{n.cat==='Actions'?'THEN':n.cat==='Risk'?'WITH':'AND'}</div>}
                  <div className={cx('node',sel===n.uid&&'on')} onClick={()=>setSel(n.uid)}>
                    <span className="node-ico">{n.icon}</span>
                    <div style={{flex:1,minWidth:0}}>
                      <div className="node-nm">{n.name}</div>
                      <div className="node-sub">{n.params}</div>
                    </div>
                    <span className="status-pill" style={{background:'var(--bg-base)',color:'var(--tx-3)'}}>{n.cat}</span>
                    <button className="node-x" onClick={e=>{ e.stopPropagation(); removeNode(n.uid); }} aria-label="Remove block">✕</button>
                  </div>
                </React.Fragment>
              ))}
            </div>
          ):(
            <div className="code-prev">
              {code.split('\n').map((l,i)=><div key={i}>{highlightCode(l)||'\u00A0'}</div>)}
            </div>
          )}
        </div>

        {/* ── Inspector ── */}
        <div className="card card-p">
          <div className="card-hd"><div className="card-title">⚙ Inspector</div></div>

          <div className="form-grp">
            <label className="form-lbl">Strategy Name</label>
            <input className="form-inp" aria-label="Strategy name" value={meta.name} onChange={e=>setMeta(m=>({...m,name:e.target.value}))}/>
          </div>
          <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginTop:10}}>
            <div className="form-grp">
              <label className="form-lbl">Symbol</label>
              <select className="form-sel" value={meta.symbol} onChange={e=>setMeta(m=>({...m,symbol:e.target.value}))}>
                {['EUR/USD','GBP/USD','USD/JPY','XAU/USD','BTC/USD','NASDAQ'].map(o=><option key={o}>{o}</option>)}
              </select>
            </div>
            <div className="form-grp">
              <label className="form-lbl">Timeframe</label>
              <select className="form-sel" value={meta.tf} onChange={e=>setMeta(m=>({...m,tf:e.target.value}))}>
                {['M15','M30','H1','H4','D1'].map(o=><option key={o}>{o}</option>)}
              </select>
            </div>
          </div>

          <div className="dd-sep" style={{margin:'14px 0'}}/>

          {selNode?(
            <>
              <div className="section-lbl">Selected Block</div>
              <div className="row" style={{gap:9,marginBottom:12}}>
                <span className="node-ico">{selNode.icon}</span>
                <div>
                  <div className="node-nm">{selNode.name}</div>
                  <div className="node-sub">{selNode.cat}</div>
                </div>
              </div>
              <div className="form-grp">
                <label className="form-lbl">Parameters</label>
                <input className="form-inp" aria-label="Block parameters" value={selNode.params}
                  onChange={e=>setNodes(p=>p.map(n=>n.uid===sel?{...n,params:e.target.value}:n))}/>
              </div>
              <button className="btn btn-g btn-sm btn-full" style={{marginTop:10}} onClick={()=>removeNode(sel)}>
                🗑 Remove block
              </button>
            </>
          ):(
            <Empty icon="👆" title="No block selected" sub="Click a block on the canvas to edit its parameters."/>
          )}

          <div className="dd-sep" style={{margin:'14px 0'}}/>
          <div className="section-lbl">Validation</div>
          {[
            ['Has an entry condition',nodes.some(n=>n.cat==='Conditions')],
            ['Has an action',nodes.some(n=>n.cat==='Actions')],
            ['Has a stop loss',nodes.some(n=>n.id==='sl')],
            ['Has position sizing',nodes.some(n=>n.id==='size')],
          ].map(([l,ok])=>(
            <div key={l} className="row" style={{gap:7,padding:'5px 0',fontSize:11.5,color:ok?'var(--tx-2)':'var(--tx-3)'}}>
              <span style={{color:ok?'var(--tx-ok)':'var(--tx-wrn)'}}>{ok?'✓':'⚠'}</span>{l}
            </div>
          ))}
        </div>
      </div>

      <Modal open={saveModal} onClose={()=>setSaveModal(false)} icon="💾"
        title="Save Strategy" sub="Add this strategy to your library and make it available for backtesting."
        footer={
          <>
            <button className="btn btn-g btn-md" onClick={()=>setSaveModal(false)} disabled={saving}>Cancel</button>
            <button className="btn btn-p btn-md" onClick={save} disabled={saving}>
              {saving?<><Spinner/> Saving…</>:'💾 Save Strategy'}
            </button>
          </>
        }>
        <div className="form-grp">
          <label className="form-lbl">Name</label>
          <input className="form-inp" aria-label="Strategy name" value={meta.name} onChange={e=>setMeta(m=>({...m,name:e.target.value}))}/>
        </div>
        <div style={{background:'rgba(139,92,246,.07)',border:'1px solid var(--bd-pu)',borderRadius:8,padding:'10px 13px',fontSize:11.5,color:'var(--tx-2)',lineHeight:1.7}}>
          <strong style={{color:'var(--tx-1)'}}>{nodes.length} blocks</strong> · {meta.symbol} · {meta.tf}<br/>
          The strategy will be saved as <em>Testing</em> status until its first backtest completes.
        </div>
      </Modal>
    </div>
  );
};
