/* ══════════════════════════════════════════════
   QUANTORYX v6 — LIVE SIGNALS PAGE
   Reuses: PageHd, Empty, Modal, toast, useInterval,
           .card / .btn / .filter-chip / .stat (v5)
══════════════════════════════════════════════ */

const SignalsPage=({go})=>{
  const {data,loading}=useAsync(()=>api.signals.list(),[]);
  const {data:tickData,loading:tickLoading}=useAsync(()=>api.signals.tickers(),[]);
  const [ticks,setTicks]=useState([]);
  const [flash,setFlash]=useState({});
  const [filter,setFilter]=useState('All');
  const [live,setLive]=useState(true);
  const [detail,setDetail]=useState(null);

  useEffect(()=>{ if(tickData) setTicks(tickData); },[tickData]);

  /* Simulated tick stream — replace with a WebSocket in api.js */
  useInterval(()=>{
    if(!live||!ticks.length) return;
    const i=Math.floor(Math.random()*ticks.length);
    setTicks(p=>p.map((t,ix)=>{
      if(ix!==i) return t;
      const drift=(Math.random()-0.48)*(t.px*0.0004);
      const px=+(t.px+drift).toFixed(t.px>1000?1:t.px>100?2:4);
      return {...t,px,chg:+(t.chg+drift/t.px*100).toFixed(2)};
    }));
    setFlash({[ticks[i].pair]:Math.random()>0.5?'up':'dn'});
    setTimeout(()=>setFlash({}),620);
  },live?1400:null);

  const signals=data||[];
  const filters=['All','Buy','Sell','Active'];
  const shown=signals.filter(s=>
    filter==='All'?true:
    filter==='Active'?s.status==='active':
    s.dir===filter.toLowerCase());
  const activeN=signals.filter(s=>s.status==='active').length;
  const avgConf=signals.length?Math.round(signals.reduce((a,s)=>a+s.conf,0)/signals.length):0;

  return(
    <div className="page fade-page">
      <PageHd title="Live Signals" sub="Real-time entries generated by your active strategies">
        <span className="sig-live-badge">
          <span className="sig-live-dot" style={{animation:live?undefined:'none',opacity:live?1:.4}}/>
          {live?'Streaming':'Paused'}
        </span>
        <button className="btn btn-g btn-sm" onClick={()=>setLive(l=>!l)}>{live?'⏸ Pause':'▶ Resume'}</button>
        <button className="btn btn-p btn-sm" onClick={()=>go('alerts')}>🔔 Alert Rules</button>
      </PageHd>

      <div className="stats-row" style={{gridTemplateColumns:'repeat(4,1fr)'}}>
        {[
          {l:'Open Signals',v:activeN,c:'stat-pu',i:'📡'},
          {l:'Avg Confidence',v:`${avgConf}%`,c:'stat-bl',i:'🎯'},
          {l:'Buy / Sell',v:`${signals.filter(s=>s.dir==='buy').length} / ${signals.filter(s=>s.dir==='sell').length}`,c:'stat-gr',i:'⚖'},
          {l:'Instruments',v:ticks.length,c:'stat-cy',i:'🌐'},
        ].map(s=>(
          <div key={s.l} className={cx('stat',s.c)}>
            <div className="stat-hd"><span className="stat-lbl">{s.l}</span><span className="stat-ico">{s.i}</span></div>
            <div className="stat-val">{loading?'—':s.v}</div>
          </div>
        ))}
      </div>

      <div className="sig-grid">
        <div>
          <div className="strat-filters" style={{marginBottom:12}}>
            {filters.map(f=><button key={f} className={cx('filter-chip',filter===f&&'on')} onClick={()=>setFilter(f)}>{f}</button>)}
          </div>

          {loading&&Array.from({length:3},(_,i)=><div key={i} style={{marginBottom:10}}><SkelCard rows={2}/></div>)}

          {!loading&&shown.length===0&&(
            <div className="card card-p">
              <Empty icon="📡" title="No signals match this filter"
                sub="Signals appear here the moment an active strategy triggers an entry condition."/>
            </div>
          )}

          {!loading&&shown.map(s=>(
            <div key={s.id} className={cx('sig-card',s.dir)}>
              <div className="sig-hd">
                <span className="sig-pair">{s.pair}</span>
                <span className={cx('sig-dir',s.dir)}>{s.dir.toUpperCase()}</span>
                <span className="status-pill" style={{background:'var(--bg-base)',color:'var(--tx-3)'}}>{s.tf}</span>
                {s.status!=='active'&&<span className={cx('status-pill',s.status==='filled'?'pill-ok':'pill-warn')}>{s.status}</span>}
                <span className="sig-time">{relTime(s.time)}</span>
              </div>

              <div className="sig-levels">
                {[['Entry',s.entry],['Stop Loss',s.sl],['Take Profit',s.tp],['R:R',s.rr]].map(([l,v])=>(
                  <div key={l}>
                    <div className="sig-lv-l">{l}</div>
                    <div className="sig-lv-v">{v}</div>
                  </div>
                ))}
              </div>

              <div>
                <div className="row" style={{justifyContent:'space-between',fontSize:10.5,color:'var(--tx-3)'}}>
                  <span>Confidence</span><span style={{fontWeight:600,color:'var(--tx-1)'}}>{s.conf}%</span>
                </div>
                <div className="sig-bar"><div className="sig-bar-f" style={{width:`${s.conf}%`}}/></div>
              </div>

              <div className="sig-foot">
                <span className="sig-src">📋 {s.strategy}</span>
                <div style={{marginLeft:'auto',display:'flex',gap:7}}>
                  <button className="btn btn-g btn-sm" onClick={()=>setDetail(s)}>Details</button>
                  <button className="btn btn-p btn-sm" onClick={()=>toast.success('Order staged',`${s.dir.toUpperCase()} ${s.pair} @ ${s.entry} queued for execution.`)}>
                    ⚡ Execute
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="card card-p">
          <div className="card-hd">
            <div className="card-title">🌐 Market Watch</div>
            <span className="sig-live-badge" style={{fontSize:9,padding:'2px 7px'}}>
              <span className="sig-live-dot" style={{animation:live?undefined:'none'}}/>LIVE
            </span>
          </div>
          {tickLoading?<SkelTable rows={8} cols={3}/>:(
            <div className="sig-feed">
              {ticks.map(t=>(
                <div key={t.pair} className={cx('tick-row',flash[t.pair]==='up'&&'tick-flash-up',flash[t.pair]==='dn'&&'tick-flash-dn')}>
                  <span className="tick-pair">{t.pair}</span>
                  <span className="tick-px">{t.px.toLocaleString('en-US',{minimumFractionDigits:t.px>1000?1:t.px>100?2:4})}</span>
                  <span className={cx('tick-chg',t.chg>=0?'up':'down')}>{t.chg>=0?'+':''}{t.chg.toFixed(2)}%</span>
                </div>
              ))}
            </div>
          )}
          <div style={{fontSize:10,color:'var(--tx-3)',marginTop:10,textAlign:'center'}}>
            Prices are simulated · swap to a WebSocket feed in <code style={{fontFamily:'JetBrains Mono,monospace'}}>api.signals</code>
          </div>
        </div>
      </div>

      <Modal open={!!detail} onClose={()=>setDetail(null)} size="lg" icon={detail?.dir==='buy'?'📈':'📉'}
        title={detail?`${detail.pair} · ${detail.dir.toUpperCase()} signal`:''}
        sub={detail?`${detail.strategy} · ${detail.tf} · generated ${relTime(detail.time)}`:''}
        footer={
          <>
            <span className="mdl-ft-l">Risk 2% of equity per the active money-management rule.</span>
            <button className="btn btn-g btn-md" onClick={()=>setDetail(null)}>Dismiss</button>
            <button className="btn btn-p btn-md" onClick={()=>{ toast.success('Order staged',`${detail.pair} queued.`); setDetail(null); }}>⚡ Execute</button>
          </>
        }>
        {detail&&(
          <>
            <div className="bt-kpi-row" style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:10}}>
              {[['Entry',detail.entry,'neu'],['Stop Loss',detail.sl,'err'],['Take Profit',detail.tp,'ok'],['Risk:Reward',detail.rr,'neu']].map(([l,v,c])=>(
                <div key={l} className="bt-kpi">
                  <div className="bt-kpi-lbl">{l}</div>
                  <div className={cx('bt-kpi-val',c)}>{v}</div>
                </div>
              ))}
            </div>
            <div>
              <div className="section-lbl">Signal Confidence</div>
              <div className="sig-bar" style={{height:6}}><div className="sig-bar-f" style={{width:`${detail.conf}%`}}/></div>
              <div style={{fontSize:11,color:'var(--tx-2)',marginTop:7,lineHeight:1.7}}>
                The model scores this setup at <strong style={{color:'var(--tx-1)'}}>{detail.conf}%</strong> confidence based on
                trend alignment, volatility regime, and confirmation from correlated instruments.
              </div>
            </div>
            <div>
              <div className="section-lbl">Rationale</div>
              <div style={{fontSize:11.5,color:'var(--tx-2)',lineHeight:1.8}}>
                {detail.dir==='buy'
                  ?`Price cleared the prior swing high on expanding volume while the ${detail.tf} trend filter remains positive. Momentum and breadth both confirm continuation, and the stop sits below structural support.`
                  :`Price rejected a well-tested supply zone with bearish divergence on the oscillator. The ${detail.tf} trend filter has rolled over and the stop sits above the invalidation high.`}
              </div>
            </div>
          </>
        )}
      </Modal>
    </div>
  );
};
